# **President's State of the University Address 2021** #

## Datapoints for dashboard/viewbook publication ##

**Enrollment rates**

* Total number of students by head count
```sql
SELECT *
FROM my_great_table

```

* Total number of full-time students
* Number of full-time equivalent students
* Percentage/number of male students
* Percentage/number of female students
* Percentage/number of non-binary students
* Percentage/number of minority students
* Percentage/number of international students
* Percentage/number of in-state students
* Percentage/number of Washington County students
* Percentage/number of out-of-state students
* Total number of adult students (as defined in the strategic plan – goal 2)
* Total number of new students enrolled
* Percentage/number of first-generation students
* Age of youngest student
* Age of oldest student

**Concurrent Enrollment rates**

* Percentage/number of Concurrent Enrollment students

**Retention rates**

**Degrees awarded each semester**

* Total number of associate degrees
* Total number of bachelor’s degrees
* Total number of master’s degrees
* Total number of certificates
* Total number of graduates

**Degrees awarded each semester**

* Total number of associate degrees
* Total number of bachelor’s degrees
* Total number of master’s degrees
* Total number of certificates
* Total number of graduates

**Total number (and overall amount) of scholarship awards funded**

**Academic Programs**

  * **Total number (and names if possible) of academic programs:**
      * Master's Degrees
      * Bachelor's Degrees
      * Associate Degrees
      * Certificates
      * Emphases
      * Minors
  
  * **Total number of addedd programs:**
      * Master's Degrees
      * Bachelor's Degrees
      * Associate Degrees
      * Certificates
      * Emphases
      * Minors

  * **Online Courses:**
      * Added
      * Total
      
**Student survey results/Career Services stats**

* Percentage of senior students rating their DSU experience as excellent or good
* Percentage of DSU graduates who are employed or entering graduate school or the military within six months of graduation
* Number of students who participated in internships, clinicals or student teaching
* Number of jobs or internships available on Handshake
* Number of employers included on Handshake

**Atwood Innovation Plaza statistics (overall totals to date as well as annual numbers)**

* Number of aspiring entrepreneurs and innovators served (through the Business Resource Center, the Makerspace, and/or the Innovation, Guidance and Solutions Center)
* Number of patent applications filed 
* Number of patents granted
* Number of new companies incubated (or businesses started)
* Number of jobs developed (as a result of companies launched)
* Number of copyrights issued
* Number of trademarks registered

**Human Resources statistics**

* Percentage of new full-time faculty that have come from another state
* Percentage of new full-time faculty that have been born in another nation
* Percentage of full-time staff that have been retained for at least three years
* Percentage of new full-time faculty who successfully complete their intermediate review
* Percentages of employees who report high levels of job satisfaction (as part of the “Great Colleges to Work For” program)
* Percentage of full-time positions paid at least 95% of the market median for the Carnegie Master’s benchmark group 
* Percentage of full-time employees able to identify and support the mission and its elements, vision and values and inspired to build a premier open, inclusive, comprehensive, polytechnic university
* Amount of Professional Development Funds awarded to faculty 
* Amount of Professional Development Funds awarded to staff
* Percentage of women in leadership positions on campus

**Advancement Department rates**

* Total fundraising revenues (annually)
* Number of employees who participate in payroll deduction giving 
* The amount given through payroll deduction giving
* Trailblazer Giving Day information
    * Total number of donors
    * Total number of new donors
    * Total funds raised
    * Increases over prior years
* Alumni Association stats
    * Number of alumni reached through newsletters, social media engagement, phone calls, and events
    * Number of alumni events held
    * Number of Alumni Legacy Scholarships granted
    
**Student-related statistics (for the Viewbook)**

* Average class size
* Average student housing cost (per month, shared & private)
* Student to faculty ratio
* Percentage of students offered scholarships, grants, or other financial aid
* Number of student clubs
* Number of students participating in intramural sports & programs

**Community Engagement statistics**

* Total volunteer hours of service that students, faculty, staff, and alumni board members have contributed throughout the community
* Total number of service projects DSU has participated in throughout the year (the service projects the above-mentioned volunteers contributed to)
* Number of annual Study Abroad experiences
    * Total programs (and destinations)
    * Number of faculty members involved
    * Number of students involved
    
**Multicultural & Inclusion Center information**

* Number of MIC events held each year
* Overall number of participants at MIC events

**Athletics statistics**

* Number of NCAA Division Teams
* Recent Championships (from the past 5 years)
* Regional tournament appearances
* Athletic Department hours of community service contributed (from athletes)

**Policies**

* Number of new
* Number of updated
* Number of retired/deleted
* Number of pending approval

**Events statistics -- estimated attendance at the following events:**

* Homecoming/D-Week
* Trailblazer Tree Lighting Celebration
* Kite Festival
* 4th of July Celebration
* DOCUTAH
* Huntsman World Senior Games
* Pioneer Legacy Events 24th of July Celebration

**University Marketing & Communication stats**

* Media Reach
* Media Mentions
* Ad Value Equivalency
* Social Media Impressions
* Social Media Engagements
* Social Media Followers













      



